apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
    appId: "{{ .Values.appId }}"
    envId: "{{ .Values.envId }}"
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      appId: "{{ .Values.appId }}"
      envId: "{{ .Values.envId }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        appId: "{{ .Values.appId }}"
        envId: "{{ .Values.envId }}"
    spec:
      containers:
      - name: app-container
        image: {{ .Values.image }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8090
          name: app-port
          protocol: TCP
