apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    choreo: "isurulucky-integration1"
  name: "isurulucky-integration1"
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo: "isurulucky-integration1"
  template:
    metadata:
      labels:
        choreo: "isurulucky-integration1"
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: "IfNotPresent"
        name: "svc-deployment"
        ports:
        - containerPort: 9090
          protocol: "TCP"
