apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: app-container
        image: {{ .Values.image }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8090
          name: app-port
          protocol: TCP
        resources:
          limits:
            cpu: 64m
            memory: 128Mi
          requests:
            cpu: 64m
            memory: 128Mi

