apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: isurulucky-myorg-myapp1
  name: isurulucky-myorg-myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isurulucky-myorg-myapp1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: isurulucky-myorg-myapp1
    spec:
      containers:
      - image: isurulucky-myorg-myapp1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8090
          name: isurulucky-myorg-myapp1
          protocol: TCP
        resources:
          limits:
            cpu: 64m
            memory: 128Mi
          requests:
            cpu: 64m
            memory: 128Mi

