apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    {{ .Values.appLabel }}: {{ .Values.appLabelValue }}
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Values.appLabel }}: {{ .Values.appLabelValue }}
  template:
    metadata:
      annotations: {}
      labels:
        {{ .Values.appLabel }}: {{ .Values.appLabelValue }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: "IfNotPresent"
        name: "deployment"
        ports:
        - containerPort: 9090
          protocol: "TCP"
      nodeSelector: {}
