apiVersion: v1
kind: Service
metadata:
  labels:
    app: isurulucky-myorg-myapp1
  name: isurulucky-myorg-myapp1
spec:
  ports:
  - name: isurulucky-myorg-myapp1
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: isurulucky-myorg-myapp1

