apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appLabelValue }}
  name: {{ .Values.appName }}
spec:
  ports:
  - name: {{ .Values.appName }}-port
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: {{ .Values.appLabelValue }}

