apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    choreo: "isurulucky-integration1"
  name: "isurulucky-integration1"
spec:
  ports:
  - name: "http-helloworldep-svc"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    choreo: "isurulucky-integration1"
