apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    {{ .Values.appLabel }}: {{ .Values.appLabelValue }}
  name: {{ .Values.appName }}
spec:
  ports:
  - name: "http"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    {{ .Values.appLabel }}: {{ .Values.appLabelValue }}
